# https://docs.percy.io/v1/docs/configuration
version: 1
snapshot:
  widths: [400]
  min-height: 450
agent:
  asset-discovery:
    # let Percy wait for network to fetch static resources
    # like images and fonts to avoid missing icons
    network-idle-timeout: 250 # ms
    # assets that don't change could be cached
    cache-responses: true
